Throw error if `scatac_from_fragments split` can't write to fragments files.
Throw error if `scatac_from_fragments split` can't write to fragments files,
by updating rust_htslib as both `rust_htslib::bgzf:Reader` and
`rust_htslib::bgzf:Writer` did not check if it could open a file successfully.

  https://github.com/rust-bio/rust-htslib/pull/444

This now print a traceback instead of silently failing:

    Processing contig "chr1"
    thread '<unnamed>' panicked at src/split_fragments.rs:56:37:
    Could not open file "/tmp/sample1/cellA.fragments.tsv.gz" for writing
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Traceback (most recent call last):
      File "/software/anaconda3/envs/pycistopic/bin/scatac_fragment_tools", line 8, in <module>
        sys.exit(main())
             ^^^^^^
      File "/software/scatac_fragment_tools/src/scatac_fragment_tools/cli/main.py", line 317, in main
        args.func(args)
      File "/software/scatac_fragment_tools/src/scatac_fragment_tools/cli/commands.py", line 186, in command_split_fragments_by_cell_type
        split_fragment_files_by_cell_type(
      File "/software/scatac_fragment_tools/src/scatac_fragment_tools/library/split/split_fragments_by_cell_type.py", line 79, in split_fragment_files_by_cell_type
        joblib.Parallel(n_jobs=n_cpu)(
      File "/software/anaconda3/envs/pycistopic/lib/python3.11/site-packages/joblib/parallel.py", line 1918, in __call__
        return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
      File "/software/anaconda3/envs/pycistopic/lib/python3.11/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
    pyo3_runtime.PanicException: Could not open file "/tmp/sample1/cellA.fragments.tsv.gz" for writing